import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

const nunito = Nunito({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'FV Store',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
